spring.application.name=products-mcp-server
spring.ai.mcp.server.name=products-mcp-server
spring.ai.mcp.server.protocol=STREAMABLE
server.port=8021
products.api.base-uri=${PRODUCTS_API_BASE_URI:http://localhost:8020}
